# Generated by Django 4.0.5 on 2022-06-26 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInfo',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('planName', models.TextField()),
                ('amountOptions', models.IntegerField()),
                ('tenureOptions', models.TextField()),
                ('benefitPercentage', models.IntegerField()),
                ('benefitType', models.CharField(choices=[('VOUCHER', 'Voucher'), ('CASHBACK', 'Cashback')], default='VOUCHER', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('selectedAmount', models.IntegerField()),
                ('selectedTenure', models.TextField()),
                ('depositedAmount', models.IntegerField()),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotionsApp.planinfo')),
            ],
        ),
    ]
