# Generated by Django 4.0.5 on 2022-06-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinfo',
            name='startedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='startedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
