# Generated by Django 4.0.5 on 2022-06-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotionsApp', '0002_planinfo_starteddate_userdata_starteddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planinfo',
            name='startedDate',
        ),
        migrations.AddField(
            model_name='planinfo',
            name='timePeriod',
            field=models.IntegerField(null=True),
        ),
    ]
