# Generated by Django 4.0.5 on 2022-06-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotionsApp', '0003_remove_planinfo_starteddate_planinfo_timeperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planinfo',
            name='benefitType',
        ),
    ]
