# Generated by Django 4.0.5 on 2022-06-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotionsApp', '0004_remove_planinfo_benefittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinfo',
            name='benefitType',
            field=models.CharField(choices=[('VOUCHER', 'Voucher'), ('CASHBACK', 'Cashback')], default='VOUCHER', max_length=256),
        ),
        migrations.AddField(
            model_name='planinfo',
            name='startedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='planinfo',
            name='usersNumber',
            field=models.IntegerField(null=True),
        ),
    ]
